name: Wiz Repro Scan
on: [push, workflow_dispatch]

jobs:
  wiz-iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate the Ghost File
        run: |
          # Mimicking the customer's transient file
          mkdir -p AP1002_IBMMQ/Bicep/Modules/
          cp AP1002_IBMMQ/Bicep/Modules/vm_module.bicep AP1002_IBMMQ/Bicep/Modules/2efe14c5-5b0a-405d-a447-b14b257a8a79-input.bicep

      - name: Download Wiz CLI
        run: curl -o wizcli https://wizcli.s3.amazonaws.com/wizcli && chmod +x wizcli

      - name: Authenticate Wiz CLI
        run: ./wizcli auth --id ${{ secrets.WIZ_CLIENT_ID }} --secret ${{ secrets.WIZ_CLIENT_SECRET }}

      - name: Run Wiz IaC Scan
        run: |
          ./wizcli iac scan --path . --policy "Wiz Default IaC Policy"
